# Generated by Django 5.0.6 on 2024-06-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_marca_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalles',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Detalles del producto'),
        ),
    ]
