# Generated by Django 5.0.6 on 2024-06-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
