# Generated by Django 5.0.6 on 2024-06-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_categoria_alter_producto_detalles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre de la marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='precio $'),
        ),
    ]
