# Generated by Django 5.0.6 on 2024-06-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_producto_marca_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalles',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='detalles del producto'),
        ),
    ]
